### ISSUE TITLE
请问代码中的setting是怎么来的

### ISSUE THREAD

**Issue by NonoKing** [lzx8589561/ZTool#2]
Main.qml中

    UI.ZLessWindow {
         id: window
         visible: true
         width: setting.window_width
         height: setting.window_height
    }

这几句中，这个setting.windos_width中的setting是哪里的呢？
我运行的时候显示找setting is not defined

还有Home.qml中

    Item {
        ColumnLayout{
            anchors.top: parent.top
            anchors.left: parent.left
            anchors.leftMargin: 10
            anchors.right: parent.right
            width: parent.width
            spacing: 20
            UI.ZText{
                text: "Hello "+system.username
                style: "h1"
                color: UI.ZTheme.primaryColor
            }
        }
    }

的system也是同样的问题

请问是要导入什么模块么

**Comment by lzx8589561** [comment]
main.py 88 line
context.setContextProperty("setting", setting_instance)
